#!/bin/bash
#SBATCH --job-name="MMMAE training"
#SBATCH --time=0:05:00
#SBATCH --mem=4G
#SBATCH --partition=orchid
#SBATCH --account=orchid
#SBATCH --qos=orchid
#SBATCH --gres=gpu:1
#SBATCH -o %j.out
#SBATCH -e %j.err

# executable
[ ! "$VIRTUAL_ENV" ] &&  "source .venv/bin/activate"
export HYDRA_FULL_ERROR=1
export PYTHONPATH="$PWD/src:$PYTHONPATH" # this is necessary at the moment because baseline modules are in src/
python src/FRAME_FM/training/train.py model=demonstrator_mmmae_era5 data=demonstrator_datasets_era5 trainer=default logging=mlflow_mmmae_era5