name: Tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: astral-sh/setup-uv@v7.2.0 

      - name: Install Test Dependencies
        run: |
          uv sync --extra test

      - name: Run tests
        continue-on-error: true
        run: uv run pytest