name: Tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        run: echo "testing"