name: Tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:

      - name: Install Test Dependencies
        run: |
          pip install uv
          uv pip install '.[test]'

